name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build app
      run: docker build --target komunitin-app-build --tag komunitin-app-build .

    - name: Linter
      run: docker run --rm komunitin-app-build npm run lint

    - name: Tests
      run: docker run --rm komunitin-app-build npm run test
    
    - name: Build production
      run: docker build --tag komunitin/komunitin-app .
    
    - name: Run production
      run: docker run -d -p 80:80 --rm komunitin/komunitin-app
      
    - name: Test production
      run: wget http://localhost/
    
    - name: Publish to Docker Hub
      if: github.ref == 'refs/heads/master'
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
        docker push komunitin/komunitin-app
    
    - name: Update test.komunitin.org
      if: github.ref == 'refs/heads/master'
      run: curl ${{ secrets.DEPLOY_WEBHOOK_URL }}
